### ISSUE TITLE
Feature request: Do not deleted pinned tweet.

### ISSUE THREAD

**Issue by geeknik** [jadametz/goTweetDelete#2]
Hi and thank you for this highly useful software.I don't know if the Twitter API allows for this kind of behavior but it would be really keen if we could keep the pinnned tweet from being deleted even when everything else goes into the trash.

**Comment by jadametz** [comment]
Hey @geeknik, thanks for the feature request!

It's a good one. I found myself wondering about this a few months ago. Unfortunately, it looks like via the Twitter API there's currently no way of identifying that a Tweet is pinned.

I think I've seen in other apps like this one, the ability to provide a Tweet ID (or potentially list of IDs) that can be ignored for removal. That does of course put the onus on you unfortunately. Do you think that's something that would still be useful despite the bit of manual work ahead of time?

**Comment by geeknik** [comment]
Sure, that would still be useful. Thank you for considering it.

**Comment by bogosj** [comment]
Would you consider adding another config option to allow for a list of tweet IDs?
