### ISSUE TITLE
Support multiple tweet IDs to ignore.

### ISSUE THREAD

**Issue by bogosj** [jadametz/goTweetDelete#8]
Use case: ignore both my pinned tweet and my Keybase proof tweet.

* Option 1: Convert `IgnoreID` into a list of `int64` which should allow passing comma separated IDs, and be backwards compatible with existing uses.
  * Pro: Code is less complex.
  * Con: Semantically `IgnoreID` which supports multiple IDs is a bit weird.
* Option 2: Add an additional `IgnoreIDs` value to the config which is a list of `int64`.
  * Pro: Semantics make sense.
  * Con: More complex code.
* Option 3: Replace `IgnoreID` with `IgnoreIDs`, as described in option 1.
  * Pro: Semantics make sense, and less complex code.
  * Con: Breaks existing usage.

**Comment by bogosj** [comment]
A fourth option: merge 1 and 3, support a list when passed as both `IgnoreID` and `IgnoreIDs`, remove `IgnoreID` at some point in the future.

**Comment by bogosj** [comment]
My inclination is to go with option 3 as a breaking change.

**Comment by jadametz** [comment]
I'm okay with option 3 as well. We'll just indicate the breaking the change in the version and changelog.

**Comment by bogosj** [comment]
No worries, re-opened the option 4 version against main. If you want me to switch to option 3 let me know.

**Comment by bogosj** [comment]
Option 3 is provided in #11.

**Comment by jadametz** [comment]
Pretty sweet how the code is essentially the same between the two options. Nice work!

Personally, I like option 3 and with it, think we could bring the project to `1.0.0`!

**Comment by bogosj** [comment]
SGTM. I've abandoned the option 4 PR.
